<?php

namespace Clastic\CityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DivisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DivisorRepository extends EntityRepository
{
}
